name: Build on Alt-Linux

on:
  workflow_call:
    inputs:
      os:
        description: "OS"
        type: string
        required: true
      architecture:
        description: "OS Architecture"
        type: string
        required: true

  workflow_dispatch:
    inputs:
      os:
        description: "OS"
        type: choice
        options:
          - alt:sisyphus
          - alt:p10
          - alt:p9
        required: false
        default: "alt:sisyphus"
      architecture:
        description: "OS Architecture"
        type: choice
        options:
          - i386
          - amd64
        required: false
        default: "amd64"

jobs:
  build:
    runs-on: ubuntu-latest
    name: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: docker build . --file Dockerfile --tag build-environment --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) --build-arg DISTR=${{ inputs.os }} --build-arg ARCH=${{ inputs.architecture }}

      - if: ${{ inputs.architecture == 'i386' }}
        run: docker run --privileged=true -i --log-driver=none -a stdin -a stdout -a stderr -v "$(pwd)":/app build-environment --platform linux/i386

      - if: ${{ inputs.architecture == 'amd64' }}
        run: docker run --privileged=true -i --log-driver=none -a stdin -a stdout -a stderr -v "$(pwd)":/app build-environment

      - uses: actions/upload-artifact@v4
        with:
          name: libdomain-${{ inputs.os }}-${{ inputs.architecture }}
          path: /home/builder2/RPM/RPMS/x86_64/
