name: Spellcheck

on: [ workflow_dispatch, workflow_call ]

jobs:
  spellcheck:
    name: spellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.7
        uses: actions/setup-python@v5
        with:
          python-version: 3.7

      - name: Install dependencies
        run: python -m pip install codespell

      - name: Check spelling
        run: bash script/spellcheck.sh
